cd src/calendar
bash ./update.sh
cd ../classroom
bash ./update.sh
cd ../classroom-docs
bash ./update.sh
cd ../docs
bash ./update.sh
cd ../drive
bash ./update.sh
cd ../forms
bash ./update.sh
cd ../samples
bash ./update.sh
cd ../sheets
bash ./update.sh
cd ../slides
bash ./update.sh
cd ../test
bash ./update.sh
cd ../..
clasp push