export enum MimeTypes {
  AUDIO = 'application/vnd.google-apps.audio',
  DOCS = 'application/vnd.google-apps.document',
  DRAWING = 'application/vnd.google-apps.drawing',
  DRIVE_FILE = 'application/vnd.google-apps.file',
  DRIVE_FOLDER = 'application/vnd.google-apps.folder',
  FORMS = 'application/vnd.google-apps.form',
  FUSION = 'application/vnd.google-apps.fusiontable',
  MAPS = 'application/vnd.google-apps.map',
  PHOTO = 'application/vnd.google-apps.photo',
  SLIDES = 'application/vnd.google-apps.presentation',
  APPS_SCRIPT = 'application/vnd.google-apps.script',
  SITES = 'application/vnd.google-apps.site',
  SHEETS = 'application/vnd.google-apps.spreadsheet',
  UNKNOWN = 'application/vnd.google-apps.unknown',
  VIDEO = 'application/vnd.google-apps.video',
  DRIVE_SDK = 'application/vnd.google-apps.drive-sdk',
}
