export enum CourseWorkState {
    COURSE_WORK_STATE_UNSPECIFIED = "COURSE_WORK_STATE_UNSPECIFIED",
    PUBLISHED = "PUBLISHED",
    DRAFT = "DRAFT",
    DELETED = "DELETED"
  }
  
  export enum CourseWorkType {
    COURSE_WORK_TYPE_UNSPECIFIED = "COURSE_WORK_TYPE_UNSPECIFIED",
    ASSIGNMENT = "ASSIGNMENT",
    SHORT_ANSWER_QUESTION = "SHORT_ANSWER_QUESTION",
    MULTIPLE_CHOICE_QUESTION = "MULTIPLE_CHOICE_QUESTION"
  }
  
  
export enum AnnouncementState {
    ANNOUNCEMENT_STATE_UNSPECIFIED = "ANNOUNCEMENT_STATE_UNSPECIFIED",
    PUBLISHED = "PUBLISHED",
    DRAFT = "DRAFT",
    DELETED = "DELETED"
  }
  
  export enum AssigneeMode {
    ASSIGNEE_MODE_UNSPECIFIED = "ASSIGNEE_MODE_UNSPECIFIED",
    ALL_STUDENTS = "ALL_STUDENTS",
    INDIVIDUAL_STUDENTS = "INDIVIDUAL_STUDENTS"
  }
  
  export enum SubmissionModificationMode {
    SUBMISSION_MODIFICATION_MODE_UNSPECIFIED = "SUBMISSION_MODIFICATION_MODE_UNSPECIFIED",
    MODIFIABLE_UNTIL_TURNED_IN = "MODIFIABLE_UNTIL_TURNED_IN",
    MODIFIABLE = "MODIFIABLE"  
  }
  