export enum Features {
    MULTISELECT_ENABLED = "MULTISELECT_ENABLED",
    MINE_ONLY = "MINE_ONLY",
    NAV_HIDDEN = "NAV_HIDDEN",
    SIMPLE_UPLOAD_ENABLED = "SIMPLE_UPLOAD_ENABLED",
    SUPPORT_DRIVES = "SUPPORT_DRIVES"
  };
  